-- Migration: Convert MySQL stored functions to PostgreSQL (plpgsql)
-- File: R__functions_postgres.sql
-- Note: PostgreSQL folds unquoted identifiers to lower-case. Calls like starexec.GetCompletePairs(...) (unquoted)
-- will resolve to starexec.getcompletepairs(...).

-- GetCompletePairs, GetErrorPairs, GetJobStatusDetail, GetJobStatus, GetPendingPairs and
-- IsPublic used to be defined here AND in R__procedures_and_views.sql, with different bodies
-- and return types (GetJobStatusDetail: INTEGER here, TEXT there). The two files run in
-- description order ("functions" before "procedures and views"), so on a fresh install the
-- second definition won, but on an upgrade where only this file changed Flyway re-ran only
-- this one and silently replaced the TEXT function with the INTEGER one that the Java callers
-- (Jobs.getJobStatus, NotifyUsersOfJobs, SubscribeUserToJob) cannot read.
-- The single authoritative definitions now live in R__procedures_and_views.sql, under the
-- heading "FUNCTIONS from StarFunctions.sql". Do not define them here again.
--
-- This file is kept, rather than deleted, on purpose: Flyway validation fails with "applied
-- migration not resolved locally" when an already-applied repeatable file disappears. Editing
-- it only changes its checksum, so it is re-applied once (it now contains no statements).
