apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-migrate
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  template:
    spec:
      containers:
      - name: flyway
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["sh","-c","mvn -DskipTests -Dflyway.url=$FLYWAY_URL -Dflyway.user=$FLYWAY_USER -Dflyway.password=$FLYWAY_PASSWORD flyway:migrate"]
        env:
        - name: FLYWAY_URL
          value: "jdbc:postgresql://{{ .Values.postgresql.host }}:{{ default 5432 .Values.postgresql.port }}/{{ .Values.postgresql.database }}"
        - name: FLYWAY_USER
          value: {{ .Values.postgresql.user | quote }}
        - name: FLYWAY_PASSWORD
          value: {{ .Values.postgresql.password | quote }}
      restartPolicy: OnFailure
