{{- if and .Values.persistence.enabled (not .Values.persistence.usePodmanVolumes) (not .Values.persistence.useHostPathForPodman) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.name" . }}-pvc
  labels:
    app: {{ include "chart.name" . }}
    component: app-data
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}

{{- if and .Values.postgres.persistence.enabled (not .Values.persistence.usePodmanVolumes) (not .Values.persistence.useHostPathForPodman) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "chart.name" . }}-postgres-pvc
  labels:
    app: {{ include "chart.name" . }}
    component: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  {{- if or .Values.postgres.persistence.storageClass .Values.persistence.storageClass }}
  storageClassName: {{ .Values.postgres.persistence.storageClass | default .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | default "20Gi" }}
{{- end }}
