{{- /*
Create a Kubernetes Secret only when an external secret is NOT provided.
For production prefer setting postgres.existingSecret and *not* storing secrets in values.yaml.
*/ -}}
{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.name" . }}-secret-postgres
type: Opaque
data:
  user: {{ .Values.postgres.user | b64enc | quote }}
  password: {{ .Values.postgres.password | b64enc | quote }}
  database: {{ .Values.postgres.database | b64enc | quote }}
  rootPassword: {{ .Values.postgres.rootPassword | b64enc | quote }}
{{- end }}
