{{- /*
Create a Kubernetes Secret only when an external secret is NOT provided.
For production prefer setting mysql.existingSecret and *not* storing secrets in values.yaml.
*/ -}}
{{- if not .Values.mysql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.name" . }}-secret-mysql
type: Opaque
data:
  user: {{ .Values.mysql.user | b64enc | quote }}
  password: {{ .Values.mysql.password | b64enc | quote }}
  database: {{ .Values.mysql.database | b64enc | quote }}
  rootPassword: {{ .Values.mysql.rootPassword | b64enc | quote }}
{{- end }}
