apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    app: {{ include "chart.name" . }}
spec:
  selector:
    app: {{ include "chart.name" . }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP # Podman does not support LoadBalancer or NodePort


---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-mysql
  labels:
    app: {{ include "chart.name" . }}-mysql
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: {{ include "chart.name" . }}-mysql