{{- if and .Values.migrations.enabled (ne (include "starexec.usesEmbeddedPostgres" .) "true") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-migrations
  labels:
{{ include "chart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    metadata:
      labels:
{{ include "chart.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "chart.fullname" . }}
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh","-c","exec /usr/local/bin/migrations.sh"]
          env:
            - name: STAREXEC_DB_HOST
              value: "{{ .Values.postgres.host }}"
            - name: STAREXEC_DB_PORT
              value: {{ .Values.postgres.port | quote }}
            - name: STAREXEC_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret | default (printf "%s-postgres-credentials" (include "chart.fullname" .)) }}
                  key: {{ .Values.postgres.existingSecretKeys.user }}
            - name: STAREXEC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret | default (printf "%s-postgres-credentials" (include "chart.fullname" .)) }}
                  key: {{ .Values.postgres.existingSecretKeys.password }}
            - name: STAREXEC_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.existingSecret | default (printf "%s-postgres-credentials" (include "chart.fullname" .)) }}
                  key: {{ .Values.postgres.existingSecretKeys.database }}
          resources:
{{ toYaml .Values.resources.migrations | indent 12 }}
  backoffLimit: 1
{{- end }}
