apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "starexec.volumeName" (list . "data") }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
