{{- if and (eq (include "starexec.isKubernetesBackend" .) "true") .Values.kubernetes.dataPvc.existingClaim }}
{{- else if and (ne (include "starexec.isKubernetesBackend" .) "true") .Values.persistence.existingClaims.data }}
{{- else }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
{{- if eq (include "starexec.isKubernetesBackend" .) "true" }}
  name: {{ include "starexec.k8sDataPvcName" . }}
{{- else }}
  name: {{ include "starexec.volumeName" (list . "data") }}
{{- end }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
{{- if eq (include "starexec.isKubernetesBackend" .) "true" }}
  accessModes:
{{- range .Values.kubernetes.dataPvc.accessModes }}
    - {{ . }}
{{- end }}
{{- else }}
  accessModes:
    - ReadWriteOnce
{{- end }}
{{- $storageClass := .Values.persistence.storageClass }}
{{- if eq (include "starexec.isKubernetesBackend" .) "true" }}
{{- $storageClass = (.Values.kubernetes.dataPvc.storageClass | default .Values.persistence.storageClass) }}
{{- end }}
{{- if $storageClass }}
  storageClassName: {{ $storageClass | quote }}
{{- end }}
  resources:
    requests:
{{- if eq (include "starexec.isKubernetesBackend" .) "true" }}
      storage: {{ .Values.kubernetes.dataPvc.size }}
{{- else }}
      storage: {{ .Values.persistence.appDataSize }}
{{- end }}
{{- end }}
