apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "starexec.volumeName" (list . "backend") }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
{{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.backendSize }}
