{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-postgres-credentials
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  user: {{ .Values.postgres.user | quote }}
  password: {{ .Values.postgres.password | quote }}
  database: {{ .Values.postgres.database | quote }}
  rootPassword: {{ .Values.postgres.rootPassword | quote }}
{{- end }}
