{{- if not .Values.postgres.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-postgres-credentials
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgres.existingSecretKeys.user }}: {{ .Values.postgres.user | quote }}
  {{ .Values.postgres.existingSecretKeys.password }}: {{ .Values.postgres.password | quote }}
  {{ .Values.postgres.existingSecretKeys.database }}: {{ .Values.postgres.database | quote }}
  {{ .Values.postgres.existingSecretKeys.rootPassword }}: {{ .Values.postgres.rootPassword | quote }}
{{- end }}
