apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
automountServiceAccountToken: {{ if eq (include "starexec.isKubernetesBackend" .) "true" }}true{{ else }}false{{ end }}
---
{{- if eq (include "starexec.isKubernetesBackend" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "starexec.k8sJobServiceAccount" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}
