name: CI Build and Package

on:
  push:
    branches: [ UMprod, main, develop, feature/*, containerised ]
    paths:
      - 'src/**'
      - 'Makefile'
      - '!**.md'

  pull_request:
    branches: [ UMprod, develop ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build with Podman
    runs-on: ubuntu-latest
    env:
      PODMAN_VERSION: 4.0
      BUILD_IMAGE: starexec-builder

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Podman
      uses: containers/podman-action@v1
      with:
        version: ${{ env.PODMAN_VERSION }}

    - name: Cache build artifacts
      uses: actions/cache@v3
      with:
        path: |
          build/
          target/
        key: ${{ runner.os }}-build-${{ hashFiles('Makefile', '**/CMakeLists.txt') }}

    - name: Install build dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends \
          build-essential \
          libnuma-dev \
          git-core

    - name: Build executable
      run: |
        podman build -t ${{ env.BUILD_IMAGE }} .
        podman run --rm -v $(pwd):/build ${{ env.BUILD_IMAGE }} make starexec

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: starexec-binaries
        path: |
          build/**
          !build/**/*.o
