name: CI Build

on:
  push:
    branches: [ UMprod, main, develop, feature/*, containerised ]
  pull_request:
    branches: [ UMprod, main, develop, feature/*, containerised ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            make \
            gcc \
            g++ \
            git \
            libnuma-dev
          sudo rm -rf /var/lib/apt/lists/*

      - name: Create SSH directory and files
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          touch ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/authorized_keys
          chmod 600 ~/.ssh/known_hosts

      - name: Display Podman version
        run: podman --version

      - name: Reset Podman and Build with Makefile
        run: |
          make clean
          make starexec ULIMIT_FLAG=

      - name: Cleanup images and volumes after build
        run: make clean