name: Docker Build and Publish

on:
  push:
    branches: [UMprod, develop, feature/*, containerised]
    paths:
      - 'Dockerfile'
      - 'Makefile'
      - '!**.md'
  pull_request:
    branches: [UMprod, develop, feature/*, containerised]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate SSH keys
        run: |
          echo "using ssh-keygen to make pub/priv keys in the current directory"
          echo "(only if they don't already exist)"
          [ -f starexec_podman_key ] || ssh-keygen -t ed25519 -N '' -f starexec_podman_key
          mkdir -p ~/.ssh
          ssh-keyscan -H localhost >> ~/.ssh/known_hosts
          chmod 600 starexec_podman_key

      - name: Build and push Docker image
        run: |
          docker buildx create --driver docker-container --use
          docker buildx build --cache-to type=gha,mode=max --build-arg BUILDKIT_INLINE_CACHE=1 --push -t ghcr.io/${{ github.repository_owner }}/starexec:latest .