name: Docker Build and Publish

on:
  push:
    branches: [UMprod, develop, feature/*, containerised]

  pull_request:
    branches: [UMprod, develop, feature/*, containerised]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate SSH keys
        run: |
          echo "using ssh-keygen to make pub/priv keys in the current directory"
          echo "(only if they don't already exist)"
          [ -f starexec_podman_key ] || ssh-keygen -t ed25519 -N '' -f starexec_podman_key
          mkdir -p ~/.ssh
          ssh-keyscan -H localhost >> ~/.ssh/known_hosts
          chmod 600 starexec_podman_key

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/${{ github.repository }}:latest \
            --tag ghcr.io/${{ github.repository }}:${{ github.sha }} \
            --push .
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
          DOCKER_BUILDKIT: 1
          DOCKER_CONFIG: ${{ github.workspace }}
          DOCKER_HOST: unix:///var/run/docker.sock
          DOCKER_TLS_CERTDIR: /workspace/.certs
          DOCKER_TLS_VERIFY: 1
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io
          DOCKER_REPOSITORY: ${{ github.repository }}
          DOCKER_IMAGE: ${{ github.repository }}