name: Docker Build and Publish

on:
  push:
    branches:
      - UMprod
      - develop
      - 'feature/*'
      - containerised
  pull_request:
    branches:
      - UMprod
      - develop
      - 'feature/*'
      - containerised

jobs:
  build:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate SSH keys if missing
        run: |
          KEY_FILE=starexec_podman_key
          echo "Checking if SSH keys exist in the workspace..."
          if [ ! -f "$KEY_FILE" ]; then
            echo "Keys not found. Generating new SSH keys..."
            ssh-keygen -t ed25519 -N "" -f "$KEY_FILE"
          else
            echo "SSH keys already exist."
          fi
          mkdir -p ~/.ssh
          ssh-keyscan -H localhost >> ~/.ssh/known_hosts
          chmod 600 "$KEY_FILE"

      - name: Build and Push Docker Image
        run: |
          echo "Building and pushing Docker images..."
          REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker buildx build --builder ${{ steps.buildx.outputs.name }} \
            --platform linux/amd64,linux/arm64 \
            --tag ghcr.io/$REPO_LOWER:latest \
            --tag ghcr.io/$REPO_LOWER:${{ github.sha }} \
            --push .