name: Java CI

on:
  push:
    branches: [UMprod, develop, feature/*, containerised]

  pull_request:
    branches: [UMprod, develop, feature/*, containerised]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      DB_HOST: localhost
      DB_PORT: 3306
      DB_NAME: starexec
      DB_USER: ci_user

    services:
      mysql:
        image: mariadb:10.3
        env:
          MARIADB_ROOT_PASSWORD: rootpassword
          MARIADB_DATABASE: ${{ env.DB_NAME }}
          MARIADB_USER: ${{ env.DB_USER }}
          MARIADB_PASSWORD: userpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          target/
        key: ${{ runner.os }}-java-${{ hashFiles('pom.xml', 'build.xml') }}

    - name: Database setup
      run: |
        mysql -h ${{ env.DB_HOST }} -P ${{ env.DB_PORT }} -u root -p rootpassword \
          -e "GRANT ALL PRIVILEGES ON ${{ env.DB_NAME }}.* TO '${{ env.DB_USER }}'@'%';"

    - name: Build with Ant
      run: ant -Dbuild.compiler=modern build

    - name: Run tests
      run: ant -Djava.security.egd=file:/dev/./urandom test

    - name: Code coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: target/site/jacoco/

    - name: Publish to GitHub Packages
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      