name: Java CI

on:
  push:
    branches: [ UMprod, main, develop, feature/*, containerised ]
  pull_request:
    branches: [ UMprod, main, develop, feature/*, containerised ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mariadb:10.3
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: starexec
          MYSQL_USER: se_admin
          MYSQL_PASSWORD: dfsdf34RFerfg3TFGRfrF3edFVg12few2
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ant ruby ruby-dev rubygems g++ make curl tar

    - name: Configure MariaDB
      run: |
        mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS starexec;"
        mysql -h 127.0.0.1 -u root -proot -e "GRANT ALL PRIVILEGES ON starexec.* TO 'se_admin'@'%' IDENTIFIED BY 'dfsdf34RFerfg3TFGRfrF3edFVg12few2';"
        mysql -h 127.0.0.1 -u root -proot -e "FLUSH PRIVILEGES;"

    - name: Install Sass
      run: sudo gem install sass --no-user-install

    - name: Create project directories
      run: |
        sudo mkdir -p /home/starexec/data_dir
        sudo chmod -R 755 /home/starexec
        sudo mkdir -p /local/sandbox
        sudo chmod 770 /local/sandbox

    - name: Setup Tomcat
      run: |
        export TOMCAT_VERSION=7.0.109
        export MYSQL_CON_VERSION=8.0.30
        sudo mkdir -p /project && cd /project
        sudo curl -fsSL https://archive.apache.org/dist/tomcat/tomcat-7/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz | sudo tar -xz
        sudo mv apache-tomcat-${TOMCAT_VERSION} apache-tomcat-7
        sudo curl -fsSL -o /project/apache-tomcat-7/lib/mysql-connector-java-${MYSQL_CON_VERSION}.jar \
          https://search.maven.org/remotecontent?filepath=mysql/mysql-connector-java/${MYSQL_CON_VERSION}/mysql-connector-java-${MYSQL_CON_VERSION}.jar

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Ant
      run: ant build

    - name: Run tests
      run: ant test